## Add a comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  "chai", # Chai v.5 now only supports EcmaScript Modules (ESM) - no require('chi')
  "eslint", # Upgrade is breaking due to peer dependencies
]
