serve:
  public:
    base_url: http://kratos.${COMPOSE_DOMAIN}/
    cors:
      enabled: true
      allowed_origins:
        - http://${COMPOSE_DOMAIN}
        - http://auth.${COMPOSE_DOMAIN}
      allow_credentials: true
  admin:
    base_url: http://kratos-admin.${COMPOSE_DOMAIN}/

cookies:
  domain: ${COMPOSE_DOMAIN}
  same_site: Lax

selfservice:
  default_browser_return_url: http://${COMPOSE_DOMAIN}/
  allowed_return_urls:
    - http://${COMPOSE_DOMAIN}/
    - http://auth.${COMPOSE_DOMAIN}/

  methods:
    password:
      enabled: true
    code:
      enabled: true
      config:
        lifespan: 168h
    link:
      enabled: true
      config:
        lifespan: 168h
    profile:
      enabled: false

  flows:
    error:
      ui_url: http://auth.${COMPOSE_DOMAIN}/error

    settings:
      ui_url: http://auth.${COMPOSE_DOMAIN}/settings
      privileged_session_max_age: 15m
      required_aal: highest_available
      after:
        password:
          default_browser_return_url: http://${COMPOSE_DOMAIN}/

    recovery:
      enabled: true
      ui_url: http://auth.${COMPOSE_DOMAIN}/recovery
      use: link
      lifespan: 168h

    verification:
      enabled: true
      ui_url: http://auth.${COMPOSE_DOMAIN}/verification
      use: code

    logout:
      after:
        default_browser_return_url: http://${COMPOSE_DOMAIN}/

    login:
      ui_url: http://auth.${COMPOSE_DOMAIN}/login
      lifespan: 10m

    registration:
      enabled: false

session:
  cookie:
    domain: ${COMPOSE_DOMAIN}
    same_site: Lax

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-VERY-IMPORTANT-SECRET
  cipher:
    - PLEASE-CHANGE-ME-32-CHAR-CIPHER1

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://mailpit:1025/?disable_starttls=true
    from_address: noreply@mojaloop.local
    from_name: Mojaloop MCM
  templates:
    recovery:
      valid:
        email:
          subject: file:///etc/config/kratos/templates/recovery.valid.email.subject.gotmpl
          body:
            html: file:///etc/config/kratos/templates/recovery.valid.email.body.gotmpl
            plaintext: file:///etc/config/kratos/templates/recovery.valid.email.body.plaintext.gotmpl
