serve:
  cookies:
    same_site_mode: Lax
  public:
    cors:
      enabled: true
      allowed_origins:
        - "*"

urls:
  self:
    issuer: http://hydra.${COMPOSE_DOMAIN}
  consent: http://auth.${COMPOSE_DOMAIN}/consent
  login: http://auth.${COMPOSE_DOMAIN}/login
  logout: http://auth.${COMPOSE_DOMAIN}/logout

secrets:
  system:
    - PLEASE-CHANGE-ME-VERY-IMPORTANT-32C

oidc:
  subject_identifiers:
    supported_types:
      - public

strategies:
  access_token: jwt

ttl:
  access_token: 1h
  id_token: 1h
  refresh_token: 720h
  auth_code: 10m

log:
  level: debug
  format: text
  leak_sensitive_values: true
