version: 2.1
setup: true
orbs:
  build: mojaloop/build@1.0.46

jobs:
  test_coverage:
    machine: true
    environment:
      MAIN_BRANCH_NAME: main
      DEVELOP_BRANCH_NAME: fix/adoption
    steps:
      - machine_dependencies
      - checkout
      - configure_nvm
      - display_versions
      - attach_workspace:
          at: /tmp
      - run:
          name: Create dir for test results
          command: mkdir -p ./test/results
      - run:
          name: Execute integration tests
          command: |
            # Set Node version to default (Note: this is needed on Ubuntu)
            nvm use default

            echo "Running integration tests from ${DEVELOP_BRANCH_NAME} branch..."
            git checkout ${DEVELOP_BRANCH_NAME}
            npm ci
            npm run test:coverage
          environment:
            PORT: 3001
            DATABASE_HOST: localhost
            DATABASE_PORT: 3306
            DATABASE_USER: mcm
            DATABASE_PASSWORD: mcm
            DATABASE_SCHEMA: mcm
            VAULT_ENDPOINT: http://localhost:8233
            VAULT_AUTH_METHOD: TOKEN
            VAULT_TOKEN: dev-token
            VAULT_ROLE_ID_FILE: ./docker/vault/tmp/role-id
            VAULT_ROLE_SECRET_ID_FILE: ./docker/vault/tmp/secret-id
            VAULT_PKI_CLIENT_ROLE: example.com
            VAULT_PKI_SERVER_ROLE: example.com
            SWITCH_ID: switch
      - store_artifacts:
          path: ./test/results
          destination: test
      - store_test_results:
          path: ./test/results

workflows:
  setup:
    jobs:
      - build/workflow:
          filters:
            tags:
              only: /v\d+(\.\d+){2}(-[a-zA-Z-][0-9a-zA-Z-]*\.\d+)?/
          base_image: node:20-buster
      - test_coverage:
          requires:
            - build/workflow