description: >
  This job executes the integration tests for the project.
executor: machine
environment:
  MAIN_BRANCH_NAME: feat/ime-519/adoption
  PORT: 3001
  DATABASE_HOST: localhost
  DATABASE_PORT: 3306
  DATABASE_USER: mcm
  DATABASE_PASSWORD: mcm
  DATABASE_SCHEMA: mcm
  VAULT_ENDPOINT: http://localhost:8233
  VAULT_AUTH_METHOD: TOKEN
  VAULT_TOKEN: dev-token
  SWITCH_ID: switch

parameters:
  package_lock:
    type: string
    default: ''

steps:
  - machine_dependencies
  - checkout
  - configure_nvm
  - display_versions
  - attach_workspace:
      at: /tmp
  - restore_cache:
      keys:
        - npm-cache-v1-{{ checksum "package-lock.json" }}
        - npm-cache-v1-
  - run:
      name: Create dir for test results
      command: mkdir -p ./test/results
  - run:
      name: Start Backend Services
      command: |
        npm run backend:start
  - run:
      name: Execute integration tests
      command: |
        nvm use default
        echo "Running integration tests...."
        npm ci
        npm run test:integration
      environment:
        NODE_ENV: test
        UV_THREADPOOL_SIZE: 12
        WAIT_FOR_REBALANCE: 20
        TEST_INT_RETRY_COUNT: 30
        TEST_INT_RETRY_DELAY: 2
        TEST_INT_REBALANCE_DELAY: 20000
  - save_cache:
      key: npm-cache-v1-{{ checksum "package-lock.json" }}
      paths:
        - ~/.npm
  - run:
      name: Stop Backend Services
      command: |
        npm run backend:stop
      when: always
  - store_artifacts:
      path: ./test/results
      destination: test
  - store_test_results:
      path: ./test/results
