name: Code Coverage

on:
  push:
    branches: [ main, feat/ime-519/adoption ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
        
    - name: Run Coverage Tests
      run: npm run test:coverage-check
        
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: coverage/
        
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info